name: fsdl-text-recognizer-2022
channels:
  - defaults
dependencies:
  - python=3.7  # versioned to match Google Colab  # version also pinned in Dockerfile
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - pip=21.1.3  # versioned to match Google Colab  # version also pinned in Dockerfile
